

"""
A list of (lemmatized) cliches and some suggestions for replacements.
"""


# Many thanks to powerthesaurus.org and proselint.com

# pylint: disable=too-many-lines
# Yes, it's a lot, but it's all just dictionary.

CLICHES = {
    '11th hour': ['last minute'],
    'a chip off the old block': [],
    'a clean slate': [],
    'a dark and stormy night': [],
    'a far a the eye can see': [],
    'a far cry': [],
    'a fate bad than death': [],
    'a fine kettle of fish': [],
    'a good a gold': [],
    'a loose cannon': [],
    'a luck would have prp': ['fortuitously', 'fortunately', 'happily',
                              'luckily', 'mercifully'],
    'a matter of concern': [],
    'a penny save be a penny earn': [],
    'a the crow fly': ['directly', 'immediately', 'straight'],
    'a to whether': ['whether'],
    'a tough row to hoe': [],
    'a word to the wise': [],
    'about time': [],
    'ace in the hole': [],
    'achilles heel': ['failing', 'frailty', 'vulnerability', 'weakness'],
    'acid test': [],
    'action speak louder than word': [],
    'add insult to injury': [],
    'after prp own heart': ['appealing', 'compatible', 'congenial', 'kindred',
                            'like-minded'],
    'against all odds': [],
    'air dirty laundry': ['gossip', 'rumor', 'slander', 'tale'],
    'air prp dirty laundry': [],
    'ala and alack': [],
    'all fun and game': [],
    'all in a day\'s work': ['routine', 'typical', 'usual'],
    'all over the map': ['chaotic', 'disorganized', 'everywhere',
                         'ubiquitously'],
    'all prp egg in one basket': [],
    'all talk and no action': [],
    'all talk no action': [],
    'all that glitter be not gold': [],
    'all that jazz': [],
    'all the help prp can get': [],
    'all thing be equal': [],
    'all thumb': [],
    'all\'s fair in love and war': [],
    'all\'s well that end well': [],
    'almighty dollar': [],
    'american as apple pie': [],
    'an axe to grind': [],
    'an eternity': [],
    'another day another dollar': [],
    'anything go': [],
    'arm and a leg': ['cost', 'costly', 'excessive', 'exorbitant',
                      'expense', 'expensive', 'extravagant', 'overpriced',
                      'premium'],
    'arm to the teeth': ['armed'],
    'as a last resort': [],
    'as luck would have prp': [],
    'as old as time': [],
    'as the crow fly': [],
    'at all time': ['constantly', 'continually', 'invariably', 'perpetually'],
    'at loose end': [],
    'at prp wit end': [],
    'at the end of prp rope': ['desperate'],
    'at the end of the day': ['eventually', 'finally', 'ultimately'],
    'at this time': ['currently', 'given that', 'here', 'now'],
    'at wit\'s end': [],
    'attach hereto': [],
    'avoid like the plague': [],
    'babe in the wood': [],
    'baby boomer': ['postwar generation'],
    'back against the wall': [],
    'back in the saddle': [],
    'back seat driver': [],
    'back stabber': ['apostate', 'betrayer', 'defector', 'deserter',
                     'informer', 'rebel', 'recreant', 'renegade', 'traitor',
                     'turncoat'],
    'back to square one': [],
    'back to the draw board': ['beginning', 'origin', 'outset', 'start'],
    'bad blood': ['acrimony', 'animosity', 'animus', 'antagonism',
                  'antipathy', 'bitterness', 'conflict', 'enmity', 'hatred',
                  'hostility', 'malevolence', 'malice', 'rancor', 'venom'],
    'bad call': [],
    'bad hair day': [],
    'bad nightmare': [],
    'bad seed': [],
    'bad to the bone': [],
    'badge of honor': [],
    'bait and switch': ['cheat', 'collusion', 'treachery', 'trickery'],
    'bait breath': ['agitated', 'anticipating', 'anxious', 'expectant',
                    'nervous'],
    'bald face liar': [],
    'bald face lie': [],
    'ball be in prp court': [],
    'ball roll': [],
    'ballpark figure': [],
    'bang prp head against a brick wall': [],
    'baptism by fire': [],
    'bare bone': ['austere', 'core', 'foundation', 'framework', 'plain',
                  'spartan', 'stark', 'unadorned', 'unvarnished'],
    'barge in': ['encroach', 'infringe', 'interfere', 'interrupt',
                 'intrude', 'meddle'],
    'barge right in': ['encroach', 'infringe', 'interfere', 'interrupt',
                       'intrude', 'meddle'],
    'bark up the wrong tree': [],
    'bat out of hell': [],
    'be all and end all': [],
    'be the case': [],
    'be there do that': [],
    'bear down': ['crush', 'drive', 'force', 'press', 'push', 'thrust'],
    'bear yesterday': ['gullible', 'innocent', 'naïve'],
    'beat a dead horse': ['assay', 'belabor', 'dwell', 'linger',
                          'rehash', 'scrutinize'],
    'beat around the bush': ['hedge', 'intimate'],
    'beg to differ': ['disagree', 'dissent', 'oppose'],
    'beggar can\'t be chooser': [],
    'behind the eight ball': [],
    'bell and whistle': ['accessories', 'additions', 'embellishments',
                         'enhancements', 'extras', 'frills', 'gadgetry',
                         'luxuries'],
    'bend over backwards': [],
    'benefit of the doubt': [],
    'bent out of shape': ['angry', 'enraged', 'fierce', 'fuming',
                          'furious', 'indignant', 'ireful'],
    'best laid plan': [],
    'best thing since slice bread': ['delight', 'pleasure'],
    'bet prp all': ['chance', 'risk', 'venture'],
    'bet prp bottom dollar': [],
    'between a rock and a hard place': [],
    'between scylla and charybdis': [],
    'between the devil and the deep blue sea': [],
    'betwixt and between': [],
    'beyond the pale': [],
    'bide prp time': [],
    'big a a house': ['big', 'colossal', 'enormous', 'gigantic', 'huge',
                      'immense', 'large', 'massive', 'monstrous',
                      'prodigious', 'substantial', 'tremendous'],
    'big as life': [],
    'big cheese': [],
    'big fish in a small pond': [],
    'big man on campus': [],
    'big prp be the harder prp fall': [],
    'big wig': ['boss', 'brass', 'executive', 'kingpin'],
    'bigwig': ['boss', 'brass', 'executive', 'kingpin'],
    'bird and the bee': [],
    'bird in the hand': [],
    'bird of a feather flock together': [],
    'bird\'s eye view': [],
    'bit the hand that feed prp': [],
    'bite off more than prp can chew': [],
    'bite the bullet': [],
    'bite the dust': [],
    'bite the hand that feed prp': ['abandon', 'betray', 'break faith',
                                    'cross', 'deceive', 'delude', 'forsake'],
    'black as coal': [],
    'black as pitch': [],
    'black as the ace of spade': [],
    'blast from the past': [],
    'bleed heart': [],
    'bless in disguise': [],
    'blind ambition': [],
    'blind as a bat': [],
    'blind lead the blind': [],
    'blissful ignorance': [],
    'blood be thick than water': [],
    'blood sweat and tear': [],
    'blow a fuse': [],
    'blow off steam': [],
    'blow prp own horn': [],
    'blush bride': [],
    'boil down to': [],
    'bolt from the blue': [],
    'bone to pick': [],
    'bore stiff': [],
    'bore to tear': [],
    'both foot on the ground': ['businesslike', 'constructive',
                                'empirical', 'functional', 'operative',
                                'practical', 'useful'],
    'bottom line': ['core', 'crux', 'essence', 'gist', 'heart', 'kernel'],
    'bottomless pit': [],
    'bounce back': ['backfire', 'echo', 'grow', 'increase', 'rebound',
                    'recoil', 'recover', 'recuperate', 'return', 'revive'],
    'boy will be boy': [],
    'bright and early': [],
    'bring back to reality': [],
    'brings home the bacon': [],
    'broad across the beam': [],
    'broken record': [],
    'brown nose': ['abase', 'beseech', 'court', 'fawn', 'flatter', 'kowtow'],
    'brush off': ['discount', 'dismiss', 'disregard', 'ignore', 'rebuff',
                  'refuse', 'reject', 'repudiate', 'slight', 'snub', 'spurn'],
    'bulk large': [],
    'bull by the horn': [],
    'bull in a china shop': [],
    'bun in the oven': ['pregnant'],
    'burn prp bridge': [],
    'burn question': [],
    'burn the candle at both end': ['lucubrate', 'overdo', 'overextend',
                                    'slave', 'strain', 'strive'],
    'burn the midnight oil': ['elucubrate', 'lucubrate', 'moonlight', 'work'],
    'burst prp bubble': [],
    'bury the hatchet': [],
    'business a usual': ['as usual', 'as ever'],
    'busy as a bee': [],
    'but that\'s another story': [],
    'buy in': [],
    'by hook or by crook': [],
    'by no mean': [],
    'by the book': ['exact', 'lawfully', 'legally', 'strict', 'strictly'],
    'by the same token': ['futhermore', 'likewise'],
    'by the seat of prp pant': [],
    'ca n\'t stomach': ['hate'],
    'call a spade a spade': [],
    'call onto the carpet': [],
    'call prp a day': ['cease', 'conclude', 'end', 'finish', 'stop'],
    'call prp a night': ['cease', 'conclude', 'end', 'finish', 'stop'],
    'call the shot': ['command', 'control', 'dictate', 'direct',
                      'govern', 'manage', 'order', 'oversee', 'regulate',
                      'rule', 'supervise'],
    'calm before the storm': [],
    'can of worm': ['mess', 'problem', 'question', 'situation', 'snafu',
                    'trouble'],
    'case of mistaken identity': [],
    'cash cow': ['income', 'source', 'windfall'],
    'cash prp in': [],
    'cast aspersion': [],
    'cat get prp tongue': [],
    'cat nap': ['nap', 'rest', 'sleep'],
    'cat\'s meow': ['delight', 'pleasure'],
    'cat\'s pajama': ['delight', 'pleasure'],
    'catch on': ['apprehend', 'comprehend', 'grasp', 'perceive',
                 'realize', 'realize', 'recognize', 'understand'],
    'catnap': ['nap', 'rest', 'sleep'],
    'caught in the crossfire': [],
    'caught red hand': [],
    'chase a red herring': [],
    'checker past': [],
    'chew on': ['cogitate', 'consider', 'deliberate', 'meditate', 'muse',
                'ponder', 'reflect', 'ruminate', 'think'],
    'child play': ['easy'],
    'chill out': ['calm', 'cool', 'recline', 'relax', 'rest', 'settle'],
    'chip in': ['contribute', 'donate', 'give', 'help', 'participate', 'pay'],
    'chomp at the bit': [],
    'clean out': ['bankrupt', 'cleanse', 'clear', 'deplete', 'empty',
                  'evacuate', 'remove', 'ruin', 'void'],
    'clean slate': ['beginning', 'overthrow', 'overturn', 'start', 'upset'],
    'cleanliness be next to godliness': [],
    'clear as a bell': [],
    'clear as mud': [],
    'clear the air': [],
    'close call': [],
    'close to the vest': [],
    'coast to coast': [],
    'cock and bull story': [],
    'cold blood': ['aloof', 'apathetic', 'cold', 'cool', 'impassible',
                   'impassive', 'indifferent', 'insensitive', 'lukewarm',
                   'pococurante', 'senseless', 'unconcerned', 'uninterested'],
    'cold foot': ['alarm', 'anxiety', 'apprehension', 'dismay', 'dread',
                  'fear', 'fearfulness', 'fright', 'horror', 'panic',
                  'terror', 'trepidation'],
    'cold hearted': ['cool', 'disaffected', 'dull', 'estranged', 'flat',
                     'frigid', 'languid', 'obtuse', 'phlegmatic'],
    'cold shoulder': ['dismissal', 'disregard', 'rebuff', 'rebuke',
                      'rejection', 'slight', 'snub', 'spurn'],
    'come across': ['discover', 'encounter', 'find', 'meet', 'uncover'],
    'come hell or high water': [],
    'compare apple and orange': [],
    'compleat': [],
    'conspicuous by prp absence': [],
    'cookie cutter': ['alike', 'analogous', 'homogenous', 'identical',
                      'indistinguishable', 'interchangeable', 'similar',
                      'standard', 'twin', 'undifferentiated', 'uniform'],
    'cool as a cucumber': [],
    'cool calm and collect': [],
    'copasetic': ['acceptable', 'congenial', 'decent', 'fair',
                  'gratifying', 'palatable', 'satisfactory'],
    'cost a king\'s ransom': [],
    'count prp blessing': [],
    'count prp chicken': [],
    'crack of dawn': ['dawn', 'daybreak', 'daylight', 'early morning',
                      'first light', 'sunrise', 'sunup'],
    'crash course': [],
    'cream of the crop': ['best', 'choice', 'elect', 'elite', 'favorite',
                          'pick', 'prime', 'prize', 'top'],
    'creature comfort': [],
    'cross that bridge when prp come to prp': [],
    'cross the line': [],
    'crush blow': [],
    'cry like a baby': [],
    'cry over spilt milk': [],
    'cry prp a river': [],
    'crystal clear': [],
    'curiosity kill the cat': [],
    'cut and dry': [],
    'cut edge': ['change', 'forefront', 'innovation', 'innovative',
                 'latest', 'new', 'newest', 'novelty', 'vanguard'],
    'cut the mustard': [],
    'cut through the red tape': [],
    'cut to the chase': [],
    'cut to the quick': [],
    'cute as a bug ear': [],
    'cute as a button': [],
    'cute as a puppy': [],
    'dark before the dawn': [],
    'day in day out': [],
    'dead as a doornail': [],
    'dead ringer': ['clone', 'copy', 'double', 'duplicate', 'facsimile',
                    'likeness', 'match', 'replica'],
    'deal with': ['answer', 'confront', 'control', 'cope', 'dispose of',
                  'face', 'handle', 'manage', 'manipulate', 'tackle',
                  'treat', 'troubleshoot'],
    'death and destruction': [],
    'decision making process': [],
    'devil be in the detail': [],
    'dime a dozen': [],
    'dirt cheap': ['bargain', 'cheap', 'economical', 'inexpensive',
                   'reasonable'],
    'divide and conquer': [],
    'do n\'t look back': [],
    'do or die': ['formal', 'inelastic', 'inexorable', 'intractable',
                  'reserved', 'resolute', 'tough'],
    'do time': ['imprisoned'],
    'do what prp take': [],
    'dog and pony show': [],
    'dog day': [],
    'dog eat dog': [],
    'dog tire': [],
    'down and out': ['beaten', 'broke', 'defeated', 'destitute',
                     'impoverished', 'needy', 'penniless', 'poor', 'ruined',
                     'vagabond'],
    'down at the heel': [],
    'down in the dump': [],
    'down on prp luck': ['afflicted', 'cursed', 'luckless', 'penniless',
                         'unfortunate', 'unlucky'],
    'down the hatch': [],
    'down to earth': [],
    'draw a blank': ['forget'],
    'draw the line': [],
    'dream on': [],
    'dress to kill': ['dapper', 'fashionable', 'formal', 'well-dressed'],
    'dress to the nine': ['dapper', 'fashionable', 'formal', 'well-dressed'],
    'drive prp up the wall': [],
    'drop of a hat': ['easily', 'freely', 'immediately', 'instantly',
                      'promptly', 'quickly', 'rapidly', 'readily',
                      'speedily', 'suddenly'],
    'dubious distinction': [],
    'due to the fact that': ['because'],
    'dull as dishwater': [],
    'duly authorize': [],
    'dye in the wool': [],
    'eagle eye': [],
    'ear to the ground': [],
    'early bird catch the worm': [],
    'easy as pie': [],
    'easy say than do': [],
    'eat prp heart out': [],
    'eat prp word': [],
    'elephant in the room': [],
    'eleventh hour': ['last minute'],
    'emotional roller coaster': [],
    'enclose herewith': [],
    'end justifes the mean': [],
    'end justify the mean': [],
    'even the playing field': [],
    'every detail': ['everything'],
    'every dog have prp day': [],
    'every fiber of prp be': [],
    'every little detail': ['everything'],
    'every little thing': ['everything'],
    'every single': ['each'],
    'everything but the kitchen sink': [],
    'eye for an eye': [],
    'eye peel': [],
    'face the music': [],
    'fact of life': [],
    'fair weather friend': ['phony', 'hypocrite'],
    'fall by the wayside': [],
    'fall through the crack': [],
    'fan the flame': ['aggravate', 'agitate', 'arouse', 'burn', 'excite',
                      'feed', 'incense', 'nettle', 'pique', 'provoke', 'stir'],
    'fancy meeting prp here': [],
    'far be prp from prp': [],
    'far cry': ['conflict', 'departure', 'disagreement', 'discordance',
                'discrepany', 'disparate', 'dissent', 'dissimilar',
                'dissonance', 'distinctive', 'divergence', 'opposition',
                'variation'],
    'fast and loose': [],
    'fatal blow': [],
    'feast or famine': [],
    'feather friend': [],
    'feather prp nest': [],
    'few and far between': [],
    'fifteen minute of fame': [],
    'figure prp out': ['appreciate', 'comprehend', 'follow', 'learn',
                       'realize', 'recognize', 'understand', 'visualize'],
    'fill the bill': [],
    'filthy rich': ['affluent', 'flush', 'moneyed', 'opulent',
                    'prosperous', 'rich', 'wealthy'],
    'filthy vermin': [],
    'fine kettle of fish': [],
    'fine line': [],
    'finger cross': ['hopefully'],
    'fire on all cylinder': [],
    'first and foremost': [],
    'first thing first': [],
    'first thing\'s first': [],
    'fish out of water': [],
    'fishing for a compliment': [],
    'fit as a fiddle': [],
    'fit the bill': [],
    'fit to be tie': [],
    'flash in the pan': [],
    'flat as a pancake': [],
    'fleet foot': ['fast', 'urgent', 'swift', 'flying', 'breakneck'],
    'flip flop': [],
    'flip prp lid': [],
    'flog a dead horse': [],
    'fly by night': [],
    'fly on the wall': ['observer', 'onlooker', 'spectator', 'witness'],
    'fly the coop': [],
    'follow in prp footstep': ['assume', 'borrow', 'duplicate',
                               'emulate', 'follow', 'model', 'parallel'],
    'follow prp heart': [],
    'follow the leader': [],
    'fool gold': ['foolishness'],
    'for all intent and purpose': ['apparently', 'approximately',
                                   'basically', 'essentially', 'nearly',
                                   'ostensibly', 'practically'],
    'for cry out loud': [],
    'for free': [],
    'for the bird': [],
    'for the purpose of': ['to'],
    'for what it\'s worth': [],
    'force of nature': [],
    'force to be reckon with': [],
    'forgive and forget': [],
    'fox in the henhouse': [],
    'free a a bird': ['free', 'relaxed', 'unbound', 'unconfined',
                      'unencumbered'],
    'free and easy': [],
    'free as a bird': [],
    'free reign': [],
    'fresh as a daisy': [],
    'frighten to death': ['aghast', 'awestruck', 'breathless',
                          'frightened', 'pale', 'scared'],
    'from day one': ['beginning', 'firstly', 'initially', 'originally'],
    'full of hot air': ['chattering', 'garrulous', 'gossping', 'long-winded'],
    'full steam ahead': [],
    'fun in the sun': [],
    'funny business': ['deceit', 'deception', 'duplicity', 'fraud',
                       'guile', 'horseplay', 'nonsense', 'trickery'],
    'garbage in garbage out': [],
    'gentle as a lamb': [],
    'get a kick out of': [],
    'get a leg up': [],
    'get a life': [],
    'get a room': [],
    'get down and dirty': [],
    'get down': ['alight', 'deject', 'demoralize', 'depress', 'descend',
                 'dismount', 'dispirit', 'humble', 'lower', 'slip'],
    'get enough of': [],
    'get lose': ['depart', 'exit', 'leave', 'move'],
    'get off on the wrong foot': [],
    'get off': ['get away', 'exit', 'leave', 'depart', 'quit', 'retire'],
    'get prp foot wet': [],
    'get prp goat': [],
    'get prp': ['appreciate', 'comprehend', 'follow', 'learn', 'realize',
                'recognize', 'understand', 'visualize'],
    'get the lead out': [],
    'get to the bottom of': ['comprehend', 'decipher', 'decode',
                             'discover', 'disentangle', 'fathom', 'infer'],
    'get with the program': [],
    'gild the lily': [],
    'give and take': ['alternate', 'bargain', 'barter', 'commute',
                      'compromise', 'exchange', 'interchange', 'reciprocate',
                      'share', 'swap', 'switch', 'trade'],
    'give prp a rest': ['quiet', 'silent'],
    'give prp a whirl': ['try'],
    'glimmer of hope': [],
    'gloss over': ['conceal', 'cover up', 'disregard', 'dodge', 'hide',
                   'ignore', 'neglect', 'overlook'],
    'glutton for punishment': ['masochist'],
    'go against the grain': ['bother', 'disagree', 'distress', 'hurt',
                             'injure', 'trouble', 'upset'],
    'go at prp tooth and nail': [],
    'go belly up': [],
    'go crazy': [],
    'go figure': [],
    'go for broke': [],
    'go over prp head': [],
    'go overboard': ['exaggerate', 'overdo', 'overindulge'],
    'go prp one better': [],
    'go the extra mile': [],
    'go too far': ['overdo', 'overstep'],
    'go with prp gut': [],
    'go with the flow': [],
    'go without say': [],
    'golden child': [],
    'good as gold': [],
    'good call': [],
    'good deed for the day': [],
    'good thing come to those who wait': [],
    'good time be have by all': [],
    'grasp at straw': [],
    'grass be always greener': [],
    'grease lightning': [],
    'greek to prp': [],
    'green eye monster': [],
    'green thumb': [],
    'green with envy': ['bitter', 'covetous', 'envious', 'grudging',
                        'invidious', 'jealous', 'resentful', 'suspicious'],
    'grin and bear prp': ['bear', 'endure', 'perservere'],
    'grist for the mill': [],
    'ground rule': ['axiom', 'guideline', 'stipulation'],
    'grow like a weed': [],
    'gut check': [],
    'ha the ability to': ['can'],
    'hair of the dog': [],
    'hand on': ['active', 'applied', 'experienced', 'experiential',
                'experimental', 'manual', 'practical'],
    'hand to mouth': [],
    'hang in there': ['bear', 'endure', 'persevere'],
    'hang on every word': ['be attentive'],
    'happily ever after': [],
    'happy a a': ['blissful', 'cheerful', 'delighted', 'ecstatic',
                  'glad', 'joyful', 'joyous', 'merry', 'pleased'],
    'happy as a clam': [],
    'happy as a lark': [],
    'happy camper': ['blissful', 'cheerful', 'delighted', 'ecstatic',
                     'glad', 'joyful', 'joyous', 'merry', 'pleased'],
    'hard head': ['determined', 'determined', 'obstinate', 'obstinate',
                  'resolute', 'shrewd', 'stubborn', 'unyielding'],
    'hard pill to swallow': [],
    'hard to swallow': ['far-fetched', 'forced', 'improbable'],
    'hardheaded': ['determined', 'determined', 'obstinate', 'obstinate',
                   'resolute', 'shrewd', 'stubborn', 'unyielding'],
    'hare brain': ['fickle', 'foolish', 'frivolous', 'giddy', 'silly',
                   'stupid', 'trivial', 'unrealistic'],
    'harebrained': ['fickle', 'foolish', 'frivolous', 'giddy', 'silly',
                    'stupid', 'trivial', 'unrealistic'],
    'hasn\'t a clue': [],
    'have a nice day': [],
    'have a short fuse': [],
    'have high hope': [],
    'have the last laugh': [],
    'haven\'t get a row to hoe': [],
    'he\'s get prp hand full': [],
    'head honcho': [],
    'head over heel': ['completely', 'deeply', 'headlong',
                       'passionately', 'utterly', 'wildly'],
    'head up': ['alert', 'bright', 'careful', 'lively', 'sharp', 'wary'],
    'hear a pin drop': [],
    'heard prp through the grapevine': [],
    'heart breaker': [],
    'heart breaking': [],
    'heart of gold': ['benign', 'compassionate', 'gracious', 'kind', 'tender'],
    'heart\'s content': [],
    'heavy as lead': [],
    'hem and haw': [],
    'high and dry': [],
    'high and mighty': [],
    'high as a kite': [],
    'high hope': ['anticipation', 'aspiration', 'promise', 'prospect'],
    'history repeat prp': [],
    'hit below the belt': ['beguile', 'burn', 'cheat', 'defraud', 'dupe',
                           'fleece', 'mislead', 'trick'],
    'hit on': ['catch', 'discover', 'encounter', 'find', 'flirt', 'spot'],
    'hit paydirt': [],
    'hit the book': ['cram', 'learn', 'read', 'study'],
    'hit the road': ['begin', 'depart', 'leave', 'set out', 'start', 'travel'],
    'hither and yon': [],
    'hobson\'s choice': [],
    'hold a candle to': ['approach', 'equal', 'match', 'parallel'],
    'hold prp breath': ['never', 'improbable'],
    'hold prp head up high': [],
    'hold prp horse': [],
    'hold prp own': [],
    'hold prp tongue': [],
    'honest as the day be long': [],
    'horn of a dilemma': [],
    'horse of a different color': [],
    'hot under the collar': [],
    'hour of need': [],
    'ice on the cake': [],
    'if and when': [],
    'if prp catch prp drift': [],
    'if the shoe be on the other foot': [],
    'if the shoe fit': [],
    'ill fat': ['doomed', 'foreboding', 'hapless', 'inauspicious',
                'menacing', 'sinister', 'threatening', 'unfortunate',
                'unlucky'],
    'important to note': ['important'],
    'in a jam': [],
    'in a jiffy': [],
    'in a nutshell': [],
    'in a pig\'s eye': [],
    'in a pinch': [],
    'in a word': [],
    'in due time': ['finally', 'inevitably', 'soon', 'ultimately'],
    'in hot water': [],
    'in light of': [],
    'in order to': ['to'],
    'in prp dream': [],
    'in prp opinion': [],
    'in reference to': [],
    'in short supply': [],
    'in spite of the fact': ['despite', 'although'],
    'in spite of': ['despite', 'although'],
    'in term of': ['about', 'regarding'],
    'in the clear': [],
    'in the event of': ['if'],
    'in the event': ['if'],
    'in the final analysis': [],
    'in the foreseeable future': [],
    'in the gutter': [],
    'in the last analysis': [],
    'in the long run': [],
    'in the matter of': [],
    'in the nick of time': [],
    'in the process of': ['while', 'when'],
    'in the thick of prp': [],
    'innocent bystander': [],
    'it\'s a small world': [],
    'it\'s not what prp know it\'s who prp know': [],
    'it\'s only a matter of time': [],
    'ivory tower': [],
    'jack of all trade': ['multitalented', 'versatile'],
    'jockey for position': [],
    'jog prp memory': [],
    'join at the hip': [],
    'judge a book by prp cover': [],
    'jump down prp throat': [],
    'jump in with both foot': [],
    'jump on the bandwagon': [],
    'jump the gun': [],
    'jump to conclusion': [],
    'jury be out': [],
    'jury be still out': [],
    'just a hop skip and a jump': [],
    'just a minute': [],
    'just a second': [],
    'just dessert': ['comeuppance', 'justice', 'penalty', 'punishment',
                     'recompense', 'redress', 'reprisal', 'requital',
                     'retribution', 'vengeance'],
    'just the ticket': [],
    'justice be blind': [],
    'keep a stiff upper lip': [],
    'keep an eye on': [],
    'keep prp chin up': [],
    'keep prp down': ['dampen', 'muffle', 'mute', 'quash', 'stifle',
                      'subdue', 'supress'],
    'keep prp finger cross': [],
    'keep prp simple stupid': [],
    'keep the home fire burn': [],
    'keep up with the joneses': [],
    'kick prp foot up': [],
    'kick the bucket': [],
    'kick up prp heel': [],
    'kid in a candy store': [],
    'kill two bird with one stone': [],
    'king\'s ransom': ['sum', 'treasure'],
    'kiss of death': [],
    'knock off': ['copy', 'discount', 'dupe', 'duplicate', 'facsimile',
                  'fake', 'imitation', 'likeness', 'markdown', 'model',
                  'reduction', 'replica', 'reproduction'],
    'knock on wood': ['believe', 'long for'],
    'knock prp out of the park': [],
    'knock prp sock off': [],
    'know prp from adam': [],
    'know the rope': [],
    'know the score': [],
    'know where prp stand': [],
    'knuckle down': [],
    'knuckle sandwich': [],
    'knuckle under': [],
    'labor of love': [],
    'ladder of success': [],
    'land on prp foot': [],
    'lap of luxury': [],
    'last but not least': ['finally', 'in conclusion'],
    'last ditch effort': [],
    'last hurrah': [],
    'last minute': [],
    'law of the jungle': [],
    'law of the land': [],
    'lay down the law': [],
    'leap and bound': [],
    'less of two evil': [],
    'let bygone be bygone': ['absolve', 'condone', 'excuse', 'forget'],
    'let prp hair down': [],
    'let sleep dog lie': [],
    'let the cat out of the bag': [],
    'let the good time roll': [],
    'let\'s talk turkey': [],
    'letter perfect': [],
    'lick prp wound': [],
    'lie like a rug': [],
    'life\'s a bitch': [],
    'life\'s a grind': [],
    'light at the end of the tunnel': [],
    'light than a feather': [],
    'light than air': [],
    'like a glove': [],
    'like clockwork': [],
    'like father like son': [],
    'like take candy from a baby': [],
    'like there\'s no tomorrow': [],
    'line in the sand': [],
    'lion\'s share': [],
    'litmus test': ['gauge', 'measure', 'test'],
    'live and learn': [],
    'live and let live': [],
    'long and short of prp': [],
    'long lose love': [],
    'long shot': ['fluke', 'prospect', 'underdog'],
    'long time no see': ['good morrow', 'how are you', 'nice to see you'],
    'look a gift horse in the mouth': [],
    'look before prp leap': [],
    'look down prp nose': [],
    'look like death warm over': [],
    'look on the bright side': ['hope'],
    'look what the cat drag in': [],
    'loose cannon': [],
    'lose prp head': [],
    'lose prp temper': [],
    'lose track of time': [],
    'loud as a horn': [],
    'lounge lizard': [],
    'love and lose': [],
    'low man on the totem pole': [],
    'luck of the draw': [],
    'luck of the irish': [],
    'make a mockery of': [],
    'make end meet': ['conserve', 'cope', 'economize', 'manage',
                      'restrain', 'save', 'scrimp', 'skimp', 'survive'],
    'make hay while the sun shine': [],
    'make head or tail of': ['comprehend', 'decipher', 'decode',
                             'discover', 'disentangle', 'fathom', 'infer'],
    'make money hand over fist': [],
    'make or break': [],
    'make prp blood boil': [],
    'make prp day': [],
    'make sense': ['correspond', 'be consistent', 'cohere'],
    'make the best of a bad situation': [],
    'make the best of prp': [],
    'make up': ['complete', 'compose', 'comprise', 'concoct',
                'constitute', 'construct', 'contrive', 'create', 'devise',
                'fabricate', 'form', 'formulate', 'invent', 'make'],
    'male chauvinism': [],
    'man of few word': [],
    'man\'s best friend': [],
    'many and diverse': [],
    'many hand make light work': [],
    'mark prp word': [],
    'matter of fact': ['correct', 'emotionless', 'lifeless', 'obdurage',
                       'plain', 'practicality', 'proper', 'prosaic', 'sober',
                       'unimaginative'],
    'matter of time': ['certainty', 'eventuality', 'inevitability'],
    'meaningful dialogue': [],
    'miss the boat on that one': [],
    'mission critical': [],
    'moment in the sun': [],
    'moment of glory': [],
    'moment of truth': [],
    'money to burn': [],
    'more in sorrow than in anger': [],
    'more likely to': ['appropriate', 'inclined', 'plausible', 'probable'],
    'more power to prp': [],
    'more sin against than sin': [],
    'more than anything': ['acutely', 'avidly', 'intensely', 'vehemently'],
    'more than life prp': [],
    'more than meet the eye': [],
    'more than one way to skin a cat': [],
    'more the merrier': [],
    'move experience': [],
    'mover and shaker': [],
    'murphy\'s law': [],
    'naked as a jaybird': [],
    'naked truth': [],
    'near and dear': [],
    'neat as a pin': [],
    'necessary evil': ['essential', 'requisite', 'unavoidable'],
    'needle in a haystack': ['fruitless', 'ineffective', 'ineffectual',
                             'pointless', 'ridiculous', 'ridiculous',
                             'senseless', 'silly', 'unavailing'],
    'needle to say': ['clearly', 'consequently', 'naturally', 'obviously'],
    'needless to say': [],
    'neither here nor there': [],
    'never look back': [],
    'never say never': [],
    'nick of time': [],
    'night and day': ['constantly', 'continually', 'continuously',
                      'incompatible', 'opposites', 'perennially',
                      'perpetually'],
    'nip and tuck': [],
    'nip in the bud': [],
    'nip prp in the bud': ['anticipate', 'arrest', 'control', 'cut short',
                           'foil', 'interrupt', 'preclude',
                           'prevent', 'stop', 'stymie'],
    'no accounting for taste': [],
    'no brainer': ['easy', 'obvious'],
    'no doubt': ['certainly', 'indubitably', 'likely', 'most',
                 'probably', 'undoubtedly', 'unquestionably'],
    'no go': ['abstract', 'failure', 'futile', 'impossible', 'impotent',
              'impractical', 'ineffective', 'ineffectual', 'superfluous',
              'useless', 'useless'],
    'no gut no glory': [],
    'no hold bar': ['absolutely', 'boundless', 'candidly', 'definitely',
                    'downright', 'extremely', 'frankly', 'honestly',
                    'limitless', 'outright', 'unequivocally', 'uninhibited'],
    'no love lose': [],
    'no pain no gain': [],
    'no skin off prp back': [],
    'no stone unturned': [],
    'no string attach': [],
    'no time like the present': [],
    'no use cry over spilled milk': [],
    'nose to the grindstone': [],
    'not a hope in hell': [],
    'not a minute\'s peace': [],
    'not in prp backyard': [],
    'not play with a full deck': [],
    'not the end of the world': [],
    'not write in stone': [],
    'nothing personal': [],
    'nothing to sneeze at': [],
    'nothing to write home about': ['average', 'boring', 'commonplace',
                                    'dull', 'mediocre', 'normal',
                                    'pedestrian', 'prosaic', 'typical',
                                    'undistinguished', 'uneventful',
                                    'unexceptional', 'unmemorable'],
    'nothing venture nothing gain': [],
    'now or never': [],
    'now we\'re cooking': [],
    'off guard': ['oblivious', 'unawares', 'unready', 'unsuspecting'],
    'off kilter': ['amiss', 'askew', 'bizarre', 'cranky', 'crooked',
                   'curious', 'eccentric', 'eratic', 'funny', 'listing',
                   'lopsided', 'offbeat', 'peculiar', 'quirky', 'skewed',
                   'slanted', 'slantwise', 'strange', 'tilted', 'uneven',
                   'weird'],
    'off the cuff': ['impromptu', 'improvised', 'spontaneous'],
    'off the hook': ['free', 'exempt'],
    'off the top of prp head': ['carelessly', 'immediate', 'impromptu',
                                'spontaneous', 'unplanned', 'unrehearsed'],
    'off the wagon': [],
    'off the wall': [],
    'old and wiser': [],
    'old hat': [],
    'old school': ['anachronistic', 'ancient', 'antiquated', 'antique',
                   'backward', 'conformist', 'conservative', 'conventional',
                   'customary', 'old', 'outmoded', 'past', 'purist',
                   'quaint', 'traditional', 'vintage'],
    'old than dirt': [],
    'old than methuselah': [],
    'olden day': [],
    'on a limb': ['alarming', 'dangerous', 'erratic', 'hazardous',
                  'insecure', 'perilous', 'risky', 'unsafe'],
    'on a roll': ['auspicious', 'blessed', 'favored', 'fortuitous',
                  'fortunate', 'hot', 'lucky', 'promising', 'winning'],
    'on cloud nine': [],
    'on pin and needle': [],
    'on prp toe': ['alert', 'attentive', 'aware', 'bright', 'careful',
                   'lively', 'observant', 'perceptive', 'quick', 'ready',
                   'sharp', 'vigilant', 'watchful'],
    'on the back burner': ['deferred', 'delayed', 'interrupted',
                           'postpone', 'suspended'],
    'on the ball': ['able', 'adept', 'alert', 'astute', 'attentive',
                    'aware', 'clever', 'competent', 'keen', 'perceptive',
                    'ready', 'sharp', 'shrewd', 'smart', 'vigilant',
                    'watchful'],
    'on the bandwagon': [],
    'on the fly': [],
    'on the money': [],
    'on the nose': [],
    'on the right track': [],
    'on the rock': [],
    'on the same page': ['in agreement', 'in accord'],
    'on the spot': [],
    'on the tip of prp tongue': [],
    'on the wagon': [],
    'on thin ice': [],
    'on track': ['correct', 'right', 'successful'],
    'once again': ['again'],
    'once bitten twice shy': [],
    'one bad apple doesn\'t spoil the bushel': [],
    'one bear every minute': [],
    'one brick short': [],
    'one fell swoop': ['as one', 'collectively', 'combined',
                       'concertedly', 'concurrently', 'conjointly',
                       'en masse', 'jointly', 'mutually', 'together'],
    'one foot in the grave': [],
    'one in a million': [],
    'one in million': ['blessing', 'marvel', 'prodigy', 'rarity',
                       'sensation', 'spectacle', 'winner', 'wonder',
                       'wunderkind'],
    'one night stand': ['affair', 'date', 'engagement', 'meeting',
                        'rendezvous', 'tryst'],
    'one red cent': [],
    'only game in town': [],
    'open a can of worm': [],
    'open and shut case': [],
    'open book': [],
    'open the flood gate': [],
    'opportunity doesn\'t knock twice': [],
    'out of pocket': [],
    'out of sight out of mind': [],
    'out of the frying pan into the fire': [],
    'out of the wood': ['better', 'cured', 'healed', 'healthier', 'mending',
                        'recovered', 'well'],
    'out of whack': ['defective', 'disrepair', 'down', 'ruined'],
    'out on a limb': [],
    'out to lunch': [],
    'over a barrel': [],
    'over and over': ['frequently', 'often'],
    'over the hump': [],
    'over the top': ['ardent', 'excessive', 'fanatical', 'fervent',
                     'feverish', 'manic', 'obsessive', 'overzealous',
                     'too much'],
    'pain and suffering': [],
    'pain in the': [],
    'pale in comparison': [],
    'pandora\'s box': [],
    'panic button': [],
    'par for the course': [],
    'part and parcel': [],
    'party pooper': [],
    'pas the buck': [],
    'pass away': ['decease', 'deliver', 'die', 'expire', 'give',
                  'impart', 'perish', 'succumb', 'transfer', 'transmit'],
    'pass on': ['decease', 'deliver', 'die', 'expire', 'give', 'impart',
                'perish', 'succumb', 'transfer', 'transmit'],
    'path of least resistance': [],
    'patience be a virtue': [],
    'pay through the nose': [],
    'peachy': ['divine', 'excellent', 'fine', 'great', 'keen', 'lovely',
               'marvelous', 'neat', 'pleasant', 'quality', 'satisfactory',
               'superb'],
    'penny pincher': [],
    'perfect storm': [],
    'piece of cake': ['easy', 'simple'],
    'pig in a poke': [],
    'pile prp on': [],
    'pillar of the community': [],
    'pin prp hope on': [],
    'pitter patter of little foot': [],
    'plain and simple': ['austere', 'plain', 'simple'],
    'plain as day': [],
    'plain as the nose on prp face': [],
    'play by the rule': [],
    'play prp by ear': ['improvise'],
    'play prp card right': [],
    'play the field': ['dally', 'date', 'flirt', 'gallivant', 'philander'],
    'play with fire': ['chance', 'endanger', 'hazard', 'risk', 'venture'],
    'please as punch': [],
    'please feel free to': [],
    'plenty of fish in the sea': [],
    'point with pride': [],
    'poor as a church mouse': [],
    'pot call the kettle black': [],
    'presidential timber': [],
    'press for time': ['breathless', 'hurried'],
    'pretty as a picture': [],
    'prp ain\'t over till the fat lady sings': [],
    'prp bad': ['excuse me', 'I\'m sorry'],
    'prp be hereby advise that': [],
    'prp be pleased to advice': [],
    'prp be possible': ['can', 'could', 'may', 'might'],
    'prp be what prp eat': [],
    'prp beg to differ': [],
    'prp can imagine': [],
    'prp can run but prp can\'t hide': [],
    'prp go without say': [],
    'prp good half': [],
    'prp hand be tie': ['helpless', 'indefensible', 'powerless'],
    'prp only live once': [],
    'prp own worst enemy': [],
    'prp regret to inform prp': [],
    'prp stand to reason': [],
    'prp take all kind': [],
    'prp take one to know one': [],
    'prp wish to state': [],
    'prp work cut out for prp': [],
    'pull a fast one': [],
    'pull no punch': [],
    'pull prp leg': [],
    'pull prp punch': [],
    'pure as the driven snow': [],
    'pursuant to prp request': [],
    'push the envelope': ['forge ahead', 'pioneer'],
    'put 2 and 2 together': [],
    'put one over on prp': [],
    'put prp best foot forward': [],
    'put prp foot down': [],
    'put prp in a nutshell': [],
    'put the cart before the horse': [],
    'put the pedal to the metal': [],
    'put two and two together': [],
    'quantum jump': [],
    'quantum leap': [],
    'quick as a bunny': [],
    'quick as a lick': [],
    'quick as a wink': [],
    'quick as lightning': [],
    'quiet as a dormouse': [],
    'quiet before the storm': [],
    'rag to rich': [],
    'rain bucket': [],
    'rain cat and dog': [],
    'rain on prp parade': [],
    'raise the bar': [],
    'rank and file': [],
    'rat race': [],
    'read between the line': ['deduce', 'infer', 'interpret'],
    'read the fine print': [],
    'reap what prp sow': [],
    'red as a beet': [],
    'red carpet': ['greeting', 'reception', 'welcome'],
    'red herring': ['con', 'diversion', 'feint', 'ploy', 'ruse'],
    'redound to one\'s credit': [],
    'redound to the benefit of': [],
    'regard the matter of': [],
    'reinvent the wheel': [],
    'rhyme or reason': ['rationale'],
    'rich and famous': [],
    'right up prp alley': [],
    'ring a bell': ['calls to mind', 'elicit', 'evoke', 'recall'],
    'rip prp off': [],
    'ripe old age': [],
    'rise and shine': [],
    'road less travel': [],
    'road to hell be pave with good intention': [],
    'rob peter to pay paul': [],
    'rock the boat': ['disturb', 'trouble', 'upset'],
    'rocket science': [],
    'roll over in the grave': [],
    'rough around the edge': [],
    'rub prp the wrong way': ['aggravate', 'anger', 'annoy', 'bother',
                              'disturb', 'enrage', 'grate', 'infuriate',
                              'irk', 'irritate', 'needle', 'nettle',
                              'rattle', 'try'],
    'rub the wrong way': [],
    'rule of thumb': ['guideline', 'guidepost', 'standard', 'principle',
                      'rule'],
    'rule the roost': [],
    'run circle around': ['beat', 'circumvent', 'defeat', 'devastate',
                          'exceed', 'floor', 'outdo', 'overrun', 'overwhelm',
                          'shatter', 'thrash', 'top', 'wreck'],
    'run for prp money': [],
    'run in circle': [],
    'rush for time': ['breathless', 'hurried'],
    'sad but true': [],
    'sadder but wiser': [],
    'salt of the earth': [],
    'same exact': ['same'],
    'say what prp will': ['interject'],
    'scar prp to death': ['afraid', 'aghast', 'ashen', 'blanched',
                          'cowed', 'frozen', 'horrifed', 'intimidated',
                          'pallid', 'paralysed', 'petrified', 'scared',
                          'stunned', 'terrified', 'unnerved'],
    'scar stiff': [],
    'scar to death': ['afraid', 'aghast', 'ashen', 'blanched', 'cowed',
                      'frozen', 'horrifed', 'intimidated', 'pallid',
                      'paralysed', 'petrified', 'scared', 'stunned',
                      'terrified', 'unnerved'],
    'sea change': [],
    'seal with a kiss': [],
    'second to none': [],
    'second wind': [],
    'see eye to eye': ['acquiesce', 'agree with', 'comply', 'concur'],
    'see the light': ['learn', 'reform'],
    'seize the day': [],
    'sell out': ['apostatize', 'betray', 'cross', 'defect', 'desert'],
    'sensory overload': [],
    'set prp teeth on edge': [],
    'set the record straight': [],
    'set the world on fire': [],
    'sharp as a tack': [],
    'shed light on': ['clarify', 'elucidate', 'illuminate', 'illustrate'],
    'shed some light on': ['clarify', 'elucidate', 'illuminate', 'illustrate'],
    'shirk prp duty': [],
    'shoot for the moon': [],
    'shoot the breeze': [],
    'short fuse': ['fury', 'ire', 'sensitivity', 'temper', 'temperament'],
    'shot in the dark': [],
    'shoulder to the wheel': [],
    'sick as a dog': [],
    'sigh of relief': [],
    'sign seal and deliver': [],
    'silver lining': ['bright side'],
    'sink or swim': [],
    'sit tight': ['bide', 'delay', 'linger', 'loiter', 'stay', 'wait'],
    'six of one half a dozen of another': [],
    'six of one half a dozen of the other': [],
    'skate on thin ice': [],
    'slept like a log': [],
    'sling mud': [],
    'slippery as an eel': [],
    'slippery slope': [],
    'slow and steady win the race': [],
    'slow as molasses': [],
    'slowly but surely': [],
    'smart as a whip': [],
    'smoke and mirror': ['deceit'],
    'smooth as a baby\'s bottom': [],
    'sneak suspicion': [],
    'snug as a bug in a rug': [],
    'sow wild oat': [],
    'spare the rod spoil the child': [],
    'speak of the devil': [],
    'speed of light': ['quick', 'rapid', 'speedy', 'swift'],
    'spill the bean': [],
    'spin prp wheel': [],
    'spit image of': [],
    'split second': ['instant'],
    'spoke with relish': [],
    'spread like wildfire': [],
    'spread the news': ['advertise', 'broadcast', 'circulate', 'disseminate'],
    'spread the word': ['advertise', 'broadcast', 'circulate', 'disseminate'],
    'spring to life': [],
    'spruce up': ['clean', 'neaten', 'straighten', 'tidy'],
    'square one': ['beginning', 'origin', 'outset', 'start'],
    'squeaky wheel get the grease': [],
    'stand a chance': [],
    'stand out like a sore thumb': [],
    'start from scratch': [],
    'start off': ['begin', 'commence', 'launch', 'start'],
    'state of the art': ['advanced', 'contemporary', 'fashionable',
                         'latest', 'modern', 'new', 'novel', 'popular'],
    'step on anyone\'s toe': [],
    'stick in the mud': [],
    'sticky subject': [],
    'still water run deep': [],
    'stitch in time': [],
    'stop and smell the rose': [],
    'straight as an arrow': [],
    'straw that break the camel\'s back': [],
    'stress out': [],
    'stretch to the breaking point': [],
    'strong as an ox': [],
    'stubborn as a mule': [],
    'stuff that dream be make of': [],
    'stuffed shirt': [],
    'sugarcoat': ['gloss', 'minimize', 'mollify', 'qualify', 'soften',
                  'temper'],
    'survival of the fit': ['natural selection'],
    'sweat blood': [],
    'sweat bullet': [],
    'sweeten the pot': [],
    'take a breather': ['rest'],
    'take a load off': [],
    'take any wooden nickel': [],
    'take one for the team': [],
    'take one to know one': [],
    'take prp from prp': [],
    'take stock': ['check', 'inspect', 'inventory', 'scrutinize'],
    'take the bait': [],
    'take the bull by the horn': [],
    'take the cake': ['dominate', 'triumph', 'win'],
    'take the easy way out': [],
    'take the plunge': ['dare', 'decide', 'initiate', 'launch', 'start',
                        'try', 'undertake'],
    'take two to tango': [],
    'talk shop': [],
    'team player': ['collaborator'],
    'tempt fate': ['endanger', 'gamble', 'imperil', 'jeopardize', 'risk'],
    'test the water': ['check', 'inquire', 'inspect', 'investigate',
                       'probe', 'query', 'research', 'scrutinize', 'study',
                       'survey', 'test', 'verify'],
    'than prp can shake a stick at': [],
    'that be say': [],
    'the cream of the crop': [],
    'the cream rise to the top': [],
    'the eye of the beholder': [],
    'the fact': [],
    'the more the merrier': [],
    'the real deal': [],
    'the real mccoy': [],
    'the red carpet treatment': [],
    'the same old story': [],
    'the straw that break the camel\'s back': [],
    'the whole ball of wax': ['aggregate', 'all', 'entirety',
                              'everything', 'gross', 'sum', 'total',
                              'totality', 'whole', 'work'],
    'there be no accounting for taste': [],
    'there have be': [],
    'thick as a brick': [],
    'thick as thief': [],
    'thick head': [],
    'thin as a rail': [],
    'think outside of the box': [],
    'think outside the box': [],
    'third time\'s the charm': [],
    'third wheel': ['superfluous', 'surplus'],
    'this day and age': [],
    'this hurt prp bad than prp hurt prp': [],
    'this point in time': [],
    'this will acknowledge': [],
    'thought leader': [],
    'three sheet to the wind': [],
    'through thick and thin': [],
    'throw in the towel': [],
    'throw the baby out with the bathwater': [],
    'tickle pink': ['delighted', 'elated', 'euphoric', 'glad', 'happy',
                    'joyful', 'overjoyed', 'pleased', 'thrilled'],
    'tie one on': [],
    'tie the knot': ['marry', 'wed'],
    'tight than a drum': [],
    'time after time': ['frequently', 'often'],
    'time and again': ['frequently', 'often'],
    'time and time again': [],
    'time be money': [],
    'time be of the essence': [],
    'time of day': ['time'],
    'time of prp life': ['transformative'],
    'time will tell': [],
    'tip of the iceberg': ['exterior', 'perfunctory', 'superficial'],
    'tire but happy': [],
    'to coin a phrase': [],
    'to each prp own': [],
    'to make a long story short': [],
    'to the best of prp knowledge': [],
    'to this day': ['thus far'],
    'toe the line': [],
    'tongue in cheek': ['insincere', 'ironically', 'mocking'],
    'too good to be true': [],
    'too hot to handle': [],
    'too much information': [],
    'too numerous to mention': [],
    'tooth and nail': ['hard', 'strong'],
    'top dog': ['chief', 'director', 'leader'],
    'touch and go': [],
    'touch with a ten foot pole': [],
    'tough as nail': [],
    'tread lightly': [],
    'trial and error': [],
    'trial and tribulation': [],
    'trial by fire': [],
    'tried and true': ['dependable', 'proved', 'reliable', 'safe',
                       'sure', 'trustworthy'],
    'trip down memory lane': [],
    'tune out': ['disregard', 'ignore', 'neglect', 'overlook'],
    'twist of fate': [],
    'two cent worth': [],
    'two face': ['artificial', 'backhanded', 'calculating', 'conniving',
                 'crooked', 'deceitful', 'deceptive', 'disingenuous',
                 'duplicitous', 'false', 'fickle', 'fraudulent',
                 'hypocritical', 'insincere', 'perfidious', 'scheming',
                 'treacherous', 'untrustworthy'],
    'two pea in a pod': [],
    'ugly as sin': [],
    'ultimate price': [],
    'under the counter': [],
    'under the gun': [],
    'under the same roof': [],
    'under the weather': [],
    'until the cow come home': [],
    'unvarnished truth': [],
    'up for grab': ['at hand', 'free', 'pending'],
    'up the ante': [],
    'up the creek': [],
    'uphill battle': ['formidable', 'herculean', 'involved'],
    'upper crust': [],
    'upset the applecart': [],
    'vain attempt': [],
    'vain effort': [],
    'vanquish the enemy': [],
    'various and sundry': [],
    'vested interest': [],
    'viable alternative': [],
    'wait for the other shoe to drop': [],
    'wake up call': [],
    'wakeup call': [],
    'warm welcome': [],
    'wash up': ['defeated', 'ruined'],
    'waste of time': ['bore', 'bother'],
    'watch prp p\'s and q\'s': [],
    'watch prp tongue': [],
    'watch the clock': [],
    'water under the bridge': [],
    'wax eloquent': [],
    'wax poetic': [],
    'we\'ve get a situation here': [],
    'wear many hat': ['resourceful', 'versatile'],
    'wear prp heart out on prp sleeve': [],
    'weather the storm': [],
    'weed prp out': [],
    'week of sundays': [],
    'well half': ['bedmate', 'boyfriend', 'consort', 'girlfriend', 'husband',
                  'inamorata', 'inamorato', 'mate', 'partner',
                  'significant other', 'spouse', 'sweetheart', 'wife'],
    'well late than never': [],
    'well mousetrap': [],
    'well off': ['affluent', 'prosperous', 'rich', 'wealthy'],
    'well safe than sorry': [],
    'well than ever': [],
    'wet behind the ear': [],
    'what go around come around': [],
    'what prp see be what prp get': [],
    'whatever float prp boat': [],
    'when all be say and do': [],
    'when prp rain prp pour': [],
    'when push come to shove': [],
    'when the cat\'s away': [],
    'when the go get tough the tough get go': [],
    'whet the prp appetite': [],
    'white as a sheet': [],
    'whole ball of wax': [],
    'whole hog': [],
    'whole nine yard': [],
    'wild goose chase': [],
    'will wonder never cease': [],
    'wing prp': ['improvise'],
    'winning combination': [],
    'wipe the slate clean': ['absolve', 'acquit'],
    'wisdom of the age': [],
    'wise as an owl': [],
    'witch hunt': ['stigmatization'],
    'with a grain of salt': ['doubtfully', 'skeptically'],
    'with fly color': ['well'],
    'with reference to': ['about', 'concerning', 'regarding'],
    'with regard to': ['about', 'concerning', 'regarding'],
    'wolf at the door': [],
    'wool pull over prp eye': [],
    'word fail prp': [],
    'work like a dog': [],
    'work up': ['agitated', 'aroused', 'distraught', 'emotional',
                'excited', 'feverish', 'frantic', 'frenetic', 'frenzied',
                'hysterical', 'impassioned', 'irate', 'jittery', 'nervous',
                'overwrought', 'tense', 'thrilled', 'upset'],
    'world weary': [],
    'worth prp weight in gold': [],
    'writ large': [],
    'wrong side of the bed': [],
    'yank prp chain': [],
    'yappy as a dog': [],
    'year young': [],
    'you\'re the bos': [],
    'young and foolish': [],
    'young and vibrant': [],
    }
