

cliches = {
    # Lemmatized
    '11th hour': [],
    'a far a the eye can see': [],
    'a good a gold': [],
    'a luck would have it': [],
    'a matter of time': [],
    'a the crow fly': [],
    'a to whether': ['whether'],
    'a waste of time': [],
    'about time': [],
    'achilles heel': [],
    'action speak louder than word': [],
    'after my own heart': [],
    'airing dirty laundry': [],
    'all in a day\'s work': [],
    'all in due time': [],
    'all over the map': [],
    'all talk and no action': [],
    'all that glitter is not gold': [],
    'all that jazz': [],
    'all the help he can get': [],
    'all the help i can get': [],
    'all the help she can get': [],
    'all the help they can get': [],
    'always look on the bright side': [],
    'an arm and a leg': [],
    'an eternity': [],
    'anything go': [],
    'armed to the teeth': [],
    'at all time': [],
    'at the end of my rope': [],
    'at the end of the day': [],
    'at the last minute': [],
    'at this time': [],
    'at wit\' end': [],
    'baby boomer': [],
    'back against the wall': [],
    'back seat driver': [],
    'back stabber': [],
    'back to the drawing board': [],
    'bad blood': [],
    'bad call': [],
    'bad hair day': [],
    'bad seed': [],
    'bait and switch': [],
    'baited breath': [],
    'ball is in your court': [],
    'ball rolling': [],
    'baptism by fire': [],
    'bare bone': [],
    'barge right in': [],
    'barking up the wrong tree': [],
    'bear down': [],
    'beat a dead horse': [],
    'beat around the bush': [],
    'beg to differ': [],
    'bell and whistle': [],
    'bend over backwards': [],
    'bent out of shape': [],
    'best laid plan': [],
    'best thing since sliced bread': [],
    'bet it all': [],
    'bet your bottom dollar': [],
    'better half': [],
    'better late than never': [],
    'better safe than sorry': [],
    'better than ever': [],
    'between a rock and a hard place': [],
    'big a a house': [],
    'big wig': [],
    'bite the hand that feed you': [],
    'born yesterday': [],
    'both foot on the ground': [],
    'bottom line': [],
    'bounce back': [],
    'brown nose': [],
    'brush off': [],
    'bun in the oven': [],
    'burn the candle at both end': [],
    'burn the midnight oil': [],
    'business a usual': [],
    'buy in to': [],
    'by the book': [],
    'by the same token': [],
    'by the seat of your pant': [],
    'ca n\'t stomach': [],
    'call it a day': [],
    'call the shot': [],
    'can of worm': [],
    'carry the team': [],
    'cash cow': [],
    'cash it in': [],
    'cat nap': [],
    'cat\'s meow': [],
    'catch on': [],
    'chew on': [],
    'child play': [],
    'chill out': [],
    'chip in': [],
    'clean slate': [],
    'cleaned out': [],
    'clear the air': [],
    'close call': [],
    'coast to coast': [],
    'cold foot': [],
    'cold shoulder': [],
    'cold-blooded': [],
    'come across': [],
    'cookie cutter': [],
    'copasetic': [],
    'crack of dawn': [],
    'cream of the crop': [],
    'cross the line': [],
    'cutting edge': [],
    'dead ringer': [],
    'deal with it': [],
    'dealt a fatal blow': [],
    'death and destruction': [],
    'dirt cheap': [],
    'do n\'t hold your breath': [],
    'do n\'t look back': [],
    'do or die': [],
    'do what it take': [],
    'doe n\'t stand a chance': [],
    'doing time': [],
    'down and out': [],
    'down on her luck': [],
    'down on his luck': [],
    'down on their luck': [],
    'down on your luck': [],
    'draw a blank': [],
    'dream on': [],
    'dressed to kill': [],
    'dressed to the nine': [],
    'drop of a hat': [],
    'due to the fact that': ['because'],
    'elephant in the room': [],
    'eleventh hour': [],
    'emotional roller coaster': [],
    'end justifes the mean': [],
    'end justify the mean': [],
    'every detail': [],
    'every little detail': [],
    'every single': ['each'],
    'fair weather friend': [],
    'fall through the crack': [],
    'fan the flame': [],
    'fancy meeting you here': [],
    'far cry': [],
    'figure it out': [],
    'filthy rich': [],
    'fine line': [],
    'finger crossed': [],
    'fingered': [],
    'firing on all cylinder': [],
    'first thing first': [],
    'first thing\'s first': [],
    'fleet footed': [],
    'fleet-footed': [],
    'flip flop': [],
    'fly on the wall': [],
    'follow the leader': [],
    'following in her footstep': [],
    'following in his footstep': [],
    'following in their footstep': [],
    'fool gold': [],
    'for all intent and purpose': [],
    'for cry out loud': [],
    'for the purpose of': ['to'],
    'free a a bird': [],
    'free reign': [],
    'frightened to death': [],
    'from day one': [],
    'full of hot air': [],
    'funny business': [],
    'get a life': [],
    'get a room': [],
    'get down': [],
    'get enough of': [],
    'get it': [],
    'get lost': [],
    'get off': [],
    'get to the bottom of it': [],
    'give and take': [],
    'give it a rest': [],
    'give it a whirl': [],
    'glimmer of hope': [],
    'gloss over': [],
    'glutton for punishment': [],
    'go against the grain': [],
    'go crazy': [],
    'go figure': [],
    'go out on a limb': [],
    'go over his head': [],
    'go overboard': [],
    'go too far': [],
    'go with your gut': [],
    'golden child': [],
    'good call': [],
    'got off on the wrong foot': [],
    'got off': [],
    'grasping at straw': [],
    'grass is always greener on the other side': [],
    'green with envy': [],
    'grin and bear it': [],
    'ground rule': [],
    'growing like a weed': [],
    'gut check': [],
    'ha the ability to': ['can'],
    'hand on': [],
    'hang in there': [],
    'hang on every word': [],
    'happy a a': [],
    'happy camper': [],
    'hard headed': [],
    'hard to swallow': [],
    'hard-headed': [],
    'hare brained': [],
    'hare-brained': [],
    'head over heel': [],
    'head up': [],
    'heart breaker': [],
    'heart of gold': [],
    'high hope': [],
    'history repeat itself': [],
    'hit below the belt': [],
    'hit on': [],
    'hit the book': [],
    'hit the road': [],
    'hold a candle to': [],
    'ill-fated idea': [],
    'in my opinion': [],
    'in one fell swoop': [],
    'in order to': ['to'],
    'in our opinion': [],
    'in spite of the fact': ['despite', 'although'],
    'in spite of': ['despite', 'although'],
    'in term of': ['about', 'regarding'],
    'in the clear': [],
    'in the event of': ['if'],
    'in the event': ['if'],
    'in the nick of time': [],
    'in the process of': ['while', 'when'],
    'it is important to note': [],
    'it is possible': ['can', 'could', 'may', 'might'],
    'jack of all trade': [],
    'judge a book by it cover': [],
    'jury is out': [],
    'jury is still out': [],
    'just a minute': [],
    'just a second': [],
    'just dessert': [],
    'keep it down': [],
    'king\'s ransom': [],
    'knock off': [],
    'knock on wood': [],
    'knock-off': [],
    'know where you stand': [],
    'last ditch effort': [],
    'last, but not least': [],
    'lesser of two evil': [],
    'let bygone be bygone': [],
    'like a glove': [],
    'line in the sand': [],
    'litmus test': [],
    'live and learn': [],
    'lived happily ever after': [],
    'long shot': [],
    'long time no see': [],
    'look a gift horse in the mouth': [],
    'look before you leap': [],
    'looking for a needle in a haystack': [],
    'lost track of time': [],
    'make end meet': [],
    'make head or tail of': [],
    'make or break': [],
    'make sense': ['correspond', 'be consistent', 'cohere'],
    'make up': [],
    'many hand make light work': [],
    'matter of fact': [],
    'matter-of-fact': [],
    'mission critical': [],
    'more likely to': ['appropriate', 'inclined', 'plausible', 'probable'],
    'more than anything': [],
    'more than life itself': [],
    'more than meet the eye': [],
    'more the merrier': [],
    'murphy\'s law': [],
    'my bad': [],
    'my hand are tied': [],
    'near and dear to my heart': [],
    'necessary evil': [],
    'needle to say': [],
    'night and day': [],
    'nip it in the bud': [],
    'no accounting for taste': [],
    'no brainer': [],
    'no doubt': [],
    'no go': [],
    'no hold barred': [],
    'no string attached': [],
    'no time like the present': [],
    'no-brainer': [],
    'nothing personal': [],
    'nothing to sneeze at': [],
    'nothing to write home about': [],
    'now or never': [],
    'off guard': [],
    'off the cuff': [],
    'off the hook': [],
    'off the top of my head': [],
    'off-kilter': [],
    'old school': [],
    'on a roll': [],
    'on the back burner': [],
    'on the ball': [],
    'on the fly': [],
    'on the same page': [],
    'on track': [],
    'on your toe': [],
    'once again': [],
    'one in million': [],
    'one night stand': [],
    'open book': [],
    'out of pocket': [],
    'out of the wood': [],
    'out of whack': [],
    'out to lunch': [],
    'over and over': [],
    'over the top': [],
    'paled in comparison': [],
    'pandora\'s box': [],
    'par for the course': [],
    'pas away': [],
    'pas on': [],
    'path of least resistance': [],
    'piece of cake': [],
    'plain and simple': [],
    'play it by ear': [],
    'play the field': [],
    'push the envelope': [],
    'put 2 and 2 together': [],
    'put two and two together': [],
    'quiet before the storm': [],
    'rain on my parade': [],
    'raise the bar': [],
    'read between the line': [],
    'read the fine print': [],
    'red carpet treatment': [],
    'red herring': [],
    'rhyme or reason': [],
    'right up your alley': [],
    'ring a bell': [],
    'road le traveled': [],
    'rock the boat': [],
    'rocket science': [],
    'rough around the edge': [],
    'rub me the wrong way': [],
    'rule of thumb': [],
    'run circle around': [],
    'run for your money': [],
    'rushed for time': [],
    'same exact': ['same'],
    'say what you will': [],
    'scared to death': [],
    'second wind': [],
    'see eye to eye': [],
    'see the light': [],
    'sell out': [],
    'sensory overload': [],
    'shed some light on': [],
    'short fuse': [],
    'silver lining': [],
    'sit tight': [],
    'slippery slope': [],
    'slow and steady win the race': [],
    'smoke and mirror': [],
    'split second': [],
    'spread the news': [],
    'spread the word': [],
    'spruce up': [],
    'square one': [],
    'start off': [],
    'state of the art': [],
    'sticky subject': [],
    'stress out': [],
    'sugarcoat': [],
    'survival of the fittest': [],
    'sweeten the pot': [],
    'take a breather': [],
    'take it from me': [],
    'take one for the team': [],
    'take stock': [],
    'take the cake': [],
    'take the easy way out': [],
    'take the plunge': [],
    'talk shop': [],
    'team player': [],
    'tempt fate': [],
    'test the water': [],
    'that\'s just peachy': [],
    'the eye of the beholder': [],
    'the fact': [],
    'the speed of light': [],
    'the whole ball of wax': [],
    'there ha been': [],
    'there have been': [],
    'thick headed': [],
    'thick-headed': [],
    'think outside the box': [],
    'third wheel': [],
    'tickled pink': [],
    'tie the knot': [],
    'time after time': [],
    'time and again': [],
    'time is money': [],
    'time of day': ['time'],
    'time of your life': [],
    'time will tell': [],
    'tip of the iceberg': [],
    'to each his own': [],
    'to this day': [],
    'tongue in cheek': [],
    'too much information': [],
    'tooth and nail': [],
    'top dog': [],
    'touch and go': [],
    'tread lightly': [],
    'trial by fire': [],
    'tried and true': [],
    'tune out': [],
    'two faced': [],
    'two-faced': [],
    'ultimate price': [],
    'up for grab': [],
    'up the ante': [],
    'uphill battle': [],
    'wake-up call': [],
    'washed up': [],
    'wear many hat': [],
    'wear your heart out on your sleeve': [],
    'well off': [],
    'whatever float your boat': [],
    'when all is said and done': [],
    'wing it': [],
    'winning combination': [],
    'wipe the slate clean': [],
    'witch hunt': [],
    'with a grain of salt': [],
    'with flying color': [],
    'with reference to': ['regarding', 'about'],
    'with regard to': ['regarding', 'about'],
    'worked up': [],
    'you can imagine': [],
    }
