

homophone_list = [
    ['accept', 'except'],
    ['affect', 'effect'],
    ['air', 'heir'],
    ['allowed', 'aloud'],
    ['are', 'our'],
    ['ant', 'aunt'],
    ['be', 'bee'],
    ['bare', 'bear'],
    ['berry', 'bury'],
    ['board', 'bored'],
    ['brake', 'break'],
    ['but', 'butt'],
    ['buy', 'by'],
    ['capital', 'capitol'],
    ['complement', 'compliment'],
    ['creak', 'creek'],
    ['data', 'datum'],
    ['die', 'dye'],
    ['ensure', 'insure'],
    ['feat', 'feet'],
    ['fisher', 'fissure'],
    ['for', 'four'],
    ['hear', 'here'],
    ["it's", 'its'],
    ['know', 'no'],
    ['lay', 'lie'],
    ['meat', 'meet'],
    ['might', 'mite'],
    ['one', 'won'],
    ['pair', 'pear'],
    ['peak', 'peek', 'pique'],
    ['pore', 'pour'],
    ['principal', 'principle'],
    ['read', 'reed'],
    ['read', 'red'],
    ['road', 'rode'],
    ['sight', 'site'],
    ['sew', 'so'],
    ['tack', 'tact'],
    ['tail', 'tale'],
    ['than', 'then'],
    ['their', 'there', "they're"],
    ['threw', 'through'],
    ['thyme', 'time'],
    ['to', 'too', 'two'],
    ['toe', 'tow'],
    ['tore', 'tour'],
    ['weather', 'whether'],
    ['weak', 'week'],
    ['weather', 'whether'],
    ['which', 'witch'],
    ['hole', 'whole'],
    ['wheeled', 'wield'],
    ['whine', 'wine'],
    ["you're", 'your'],
    ]
